version: '3'

services:
  
  app:
    build: .
    restart: unless-stopped
    volumes:
        - ${REPO_CONFIG_PATH}/prod.env:/go/src/${REPO_NAME}/.env
    links:
        - db:db
    environment:
        - ALLOW_ORIGINS=${ALLOW_ORIGINS}
        - COOKIE_SECURE=${COOKIE_SECURE}
        - SAME_SITE=${SAME_SITE}
    networks:
      app_net:
          aliases:
              - ${REPO_NAME}
      db_net:

  db:
     image: mysql
     env_file: 
        - ${REPO_CONFIG_PATH}/database.env
     restart: unless-stopped
     volumes: 
        - ${VOLUME_PATH}/mysql/:/var/lib/mysql/
        - ${REPO_CONFIG_PATH}/db/:/docker-entrypoint-initdb.d/
     networks:
       db_net:

networks:
  app_net:
    external:
        name: api-deploy_app
  db_net:
    external:
        name: api-deploy_db
