version: '3'

services:
  
  app:
    build: .
    restart: unless-stopped
    volumes:
        - ${CONFIG_PATH}/config.yml:/go/src/config/config.yml
    networks:
      default:
        ipv4_address: ${API_IP}

  db:
     image: mysql
     env_file: 
        - ${CONFIG_PATH}/database.env
     restart: unless-stopped
     volumes: 
        - ${VOLUME_PATH}/mysql/:/var/lib/mysql/
        - ${CONFIG_PATH}/db/:/docker-entrypoint-initdb.d/
     networks:
       default:
         ipv4_address: ${DATABASE_IP}

networks:
  default:
    external:
      name: pool-network
