version: '3'

services:
  
  app:
    build: .
    restart: unless-stopped
    volumes:
        - ${REPO_CONFIG_PATH}/.env_prod:/go/src/${REPO_NAME}/.env
    links:
        - db:drops-database
    networks:
      api:
          aliases:
              - ${REPO_NAME}

  db:
     image: mysql
     env_file: 
        - ${REPO_CONFIG_PATH}/database.env
     restart: unless-stopped
     volumes: 
        - ${VOLUME_PATH}/mysql/:/var/lib/mysql/
        - ${REPO_CONFIG_PATH}/db/:/docker-entrypoint-initdb.d/
     networks:
       api:

networks:
  api:
    external:
      name: pool-network
