db:
  host: 172.2.80.5
  user: drops
  password: drops
  port: 3306
  name: drops
redis:
    url: 172.2.60.3:6379
nats:
    url: nats://172.2.60.2:4222
alloworigins:
    - "http://172.2.20.1"
cookie:
    samesite: none
    secure: false
