-- MySQL Script generated by MySQL Workbench
-- Mi 12 Aug 2020 11:42:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drops
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drops
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drops` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `drops` ;

-- -----------------------------------------------------
-- Table `drops`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`crew` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `abbreviation` VARCHAR(8) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `public_id_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Default informations about crews like VcA Hamburg, VcA Basel etc.';


-- -----------------------------------------------------
-- Table `drops`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`profile` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(64) NOT NULL,
  `birthdate` BIGINT(20) NOT NULL,
  `gender` ENUM('divers', 'male', 'female', 'none') NOT NULL DEFAULT 'none',
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `public_id_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Default informations about the profile of a supporter';


-- -----------------------------------------------------
-- Table `drops`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `street` VARCHAR(45) NULL,
  `additional` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `google_id` VARCHAR(255) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `public_id_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Address informations';


-- -----------------------------------------------------
-- Table `drops`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`avatar` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `profile_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `profile_id`),
  INDEX `fk_avatar_profile_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_avatar_profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `drops`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Avatar image of a profile';


-- -----------------------------------------------------
-- Table `drops`.`profile_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`profile_has_address` (
  `profile_id` BIGINT(20) NOT NULL,
  `address_id` BIGINT(20) NOT NULL,
  `primary` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`profile_id`, `address_id`),
  INDEX `fk_profile_has_address_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_has_address_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `drops`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `drops`.`address` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`profile_has_crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`profile_has_crew` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `profile_id` BIGINT(20) NOT NULL,
  `crew_id` BIGINT(20) NOT NULL,
  `updated` BIGINT(20) NULL,
  `created` BIGINT(20) NULL,
  PRIMARY KEY (`id`, `profile_id`, `crew_id`),
  INDEX `fk_profile_has_entity_entity1_idx` (`crew_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_has_entity_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `drops`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_entity_entity1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `drops`.`crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`crew_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`crew_meta` (
  `id` BIGINT(20) NOT NULL COMMENT '	',
  `crew_id` BIGINT(20) NOT NULL,
  `meta_key` VARCHAR(45) NOT NULL,
  `meta_value` TEXT NOT NULL,
  PRIMARY KEY (`id`, `crew_id`),
  INDEX `fk_crew_meta_crew1_idx` (`crew_id` ASC) VISIBLE,
  CONSTRAINT `fk_crew_meta_crew1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `drops`.`crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Meta informations about a crew like meeting times and places, trello boards, facebook groups etc.';


-- -----------------------------------------------------
-- Table `drops`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`, `uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`crew_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`crew_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`crew_role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`crew_role_has_permission` (
  `crew_role_id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`crew_role_id`, `permission_id`),
  INDEX `fk_crew_role_has_permission_permission1_idx` (`permission_id` ASC) VISIBLE,
  INDEX `fk_crew_role_has_permission_crew_role1_idx` (`crew_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_crew_role_has_permission_crew_role1`
    FOREIGN KEY (`crew_role_id`)
    REFERENCES `drops`.`crew_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crew_role_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `drops`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`profile_has_crew_has_crew_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`profile_has_crew_has_crew_role` (
  `profile_has_crew_id` BIGINT(20) NOT NULL,
  `crew_role_id` BIGINT(20) NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`profile_has_crew_id`, `crew_role_id`, `uuid`),
  INDEX `fk_profile_has_crew_has_crew_role_crew_role1_idx` (`crew_role_id` ASC) VISIBLE,
  INDEX `fk_profile_has_crew_has_crew_role_profile_has_crew1_idx` (`profile_has_crew_id` ASC) VISIBLE,
  UNIQUE INDEX `profile_has_crew_has_crew_rolecol_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_profile_has_crew_has_crew_role_crew_role1`
    FOREIGN KEY (`crew_role_id`)
    REFERENCES `drops`.`crew_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_crew_has_crew_role_profile_has_crew1`
    FOREIGN KEY (`profile_has_crew_id`)
    REFERENCES `drops`.`profile_has_crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`nvm_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`nvm_state` (
  `profile_has_crew_id` BIGINT(20) NOT NULL,
  `active_state` ENUM('active', 'inactive', 'requested') NOT NULL DEFAULT 'inactive',
  `primary_crew` TINYINT(1) NOT NULL DEFAULT 0,
  `nvm_expiration_date` BIGINT(20) NULL,
  PRIMARY KEY (`profile_has_crew_id`),
  CONSTRAINT `fk_nvm_state_profile_has_crew1`
    FOREIGN KEY (`profile_has_crew_id`)
    REFERENCES `drops`.`profile_has_crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`city` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `google_id` VARCHAR(255) NOT NULL,
  `crew_id` BIGINT(20) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `crew_id`),
  UNIQUE INDEX `public_id_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_city_crew1_idx` (`crew_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_crew1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `drops`.`crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Address informations';


-- -----------------------------------------------------
-- Table `drops`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`newsletter` (
  `profile_id` BIGINT(20) NOT NULL,
  `setting` ENUM('all', 'regional', 'global', 'none') NOT NULL DEFAULT 'none',
  PRIMARY KEY (`profile_id`),
  UNIQUE INDEX `profile_id_UNIQUE` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_nvm_state_copy1_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `drops`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
